project:
  type: website
  resources: assets
  output-dir: docs
  
website:
  title: "Liam Jennings"
  navbar:
    background: "#14234b"
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/liamjennings/
        target: _blank
      - icon: github
        href: https://github.com/ljennings12
        target: _blank
      - icon: file-pdf-fill
        href: assets/Liam_Jennings_Resume.pdf
        target: _blank
        
format:
  html:
    theme:
      dark:
        - darkly
        - theme_dark.scss
      light:
        - flatly
        - theme_light.scss
    toc: true
